apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      containers:
        - name: profile-app
          image: "ghcr.io/andrewemilshokry1/profile-product:12"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
